name: Basic Testing

on:

  push:

    branches:

      - main  

jobs:

  core:

    runs-on: ubuntu-latest

    name: ESLint and Jest

    steps:

    - uses: actions/checkout@v3

    - uses: bahmutov/npm-install@v1

    - run: npm run lint

    - run: npm run test
