name: 

on:

  push:

    branches:

      - main  

jobs:

  core:

    runs-on: ubuntu-latest

    name: __BLANK 3__

    steps:

    - uses: actions/checkout@v3

    - uses: bahmutov/npm-install@v1

    # - run: npm run __BLANK 4__ (Run ESLint)

    - run: npm run test
