name: Basic Testing

on:

  push:

    branches:

      - main  

jobs:

  core:

    runs-on: ubuntu-latest

    name: Jest

    steps:

    - uses: actions/checkout@v3

    - uses: bahmutov/npm-install@v1

    - run: npm run test 
      env:
        CI: true